### ISSUE TITLE
Support PHP 7.2 and above

### ISSUE THREAD

**Issue by FLasH3r** [launchdarkly/php-server-sdk#129]
**Is your feature request related to a problem? Please describe.**
Since this repository supports PHP 5.x - it uses Monolog version 1.x - which is not the latest version and is preventing me from installing latest dependencies for PHP 7.x

PHP 5.x is no longer maintained nor supported
PHP 7.2 active support ended on 30.11.2019
https://www.php.net/supported-versions.php

**Describe the solution you'd like**
Upgrade all dependencies to PHP 7.x 

**Describe alternatives you've considered**
Create a branch for PHP 7.x

**Additional context**
None

**Comment by eli-darkly** [comment]
Hi. On the subject of PHP 5.x, we've been in an ongoing discussion about when to end support for obsolete platforms like that; unfortunately we can't do it simply on the basis of them being long past EOL, because sometimes major customers are for one reason or another committed to using an old platform (this is the same reason we still support Java 7). So in the meantime we have put quite a bit of effort into keeping the code backward-compatible. This might change in the near future but it's hard to say right this minute.

However, more specifically about the Monolog dependency... for now, I wonder if simply loosening the version constraint to allow 2.x would work. The only place where our code actually calls Monolog is when we construct the default logging implementation (`new Logger("LaunchDarkly", [new ErrorLogHandler()])`) and it _looks_ to me like the calling conventions for the `Logger` and `ErrorLogHandler` constructors have not changed in 2.x, and `Logger` should still be supporting `Psr\Log\LoggerInterface`. I will try to verify that.

**Comment by eli-darkly** [comment]
The Monolog dependency has been loosened as of the 3.7.1 release.

While there's still an ongoing discussion about PHP 5.x, I'm going to close this particular issue now since the only PHP 7.x compatibility issue that was mentioned was Monolog.
