### ISSUE TITLE
PhP 8 support for apcu backward compatibility has dropped so `apc_` calls aren't supported

### ISSUE THREAD

**Issue by gerardepema** [launchdarkly/php-server-sdk#167]
**Describe the bug**
in PhP 8, support for apcu backward compatibility has dropped so `apc_` calls aren't supported
- [As of PHP 8.0.0, apcu-bc is no longer supported.](https://www.php.net/manual/en/apcu.installation.php)

**To reproduce**
File `vendor/launchdarkly/server-sdk/src/LaunchDarkly/Impl/Integrations/ApcFeatureRequesterCache.php` does a `\apc_fetch()` call on line 26

**SDK version**
4.2.4

**Comment by eli-darkly** [comment]
The `apc` integrations no longer exist as of PHP SDK 5.0.0, which has a minimum PHP version of 8. We won't be removing them in the 4.x version of the SDK because that major version still supports older versions of PHP.

**Comment by eli-darkly** [comment]
I'm not sure I would describe this as a bug in any case. This class is not used by the SDK by default; an application could theoretically reference it directly, since all classes are public in PHP, and it would work as long as it was running in an older PHP version that had the APC extension. There would be no reason to try to use it in a PHP runtime that does not have the APC extension.
